[build]
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
# Railway will automatically set PORT - don't override it